# Generated by Django 5.0.6 on 2024-06-04 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_note_can_edit_note_public_to_delete_userdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='can_edit',
            field=models.ManyToManyField(related_name='editable_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='public_to',
            field=models.ManyToManyField(related_name='readable_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
