# Generated by Django 5.0.6 on 2024-06-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_note_can_edit_alter_note_public_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='public_to',
            new_name='can_read',
        ),
    ]
