# Generated by Django 5.0.6 on 2024-06-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_note_text_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
