# Generated by Django 5.0.6 on 2024-07-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_label_user_alter_note_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='brief',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.JSONField(null=True),
        ),
    ]
