# Generated by Django 5.0.6 on 2024-07-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_text_note_brief_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(default='blue', max_length=50, null=True),
        ),
    ]
