# Generated by Django 5.0.6 on 2024-08-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='invites',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='settings',
            field=models.JSONField(null=True),
        ),
    ]
