# Generated by Django 5.0.6 on 2024-08-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_data_invites_alter_data_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='invites',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='settings',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
