# Generated by Django 5.0.6 on 2024-08-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_data_invites_alter_data_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
